### PR TITLE
updating paths to include currencyGreaterThan param for 0

### PR DESCRIPTION
**Pull request by shiqizng**
#182. 
[py-algorand-sdk](https://github.com/algorand/py-algorand-sdk/pull/507) updates for these updated tests.

### CODE REVIEW

**Comment by shiqizng** [comment]
@algochoi I had to reorder the params because json serialization in Go orders the fields alphabetically. Please have another look.

**Comment by winder** [comment]
I think there are several other fields like this where the zero value is also a valid input

**Comment by winder** [comment]
Maybe it's just GT and LT: https://github.com/algorand/indexer/pull/484

**Comment by shiqizng** [comment]
> I think there are several other fields like this where the zero value is also a valid input

maybe, we need to do some investigation to know if there are other parameters having the same issue.

**Comment by shiqizng** [comment]
> The main issue here is that it seems we can no longer distinguish between unset and set to 0. Is this an issue?

Unset and 0 are handled using None in python, String in java and js, pointer in Go, and 
we have some tests in here that have unset currencyGreaterThan values, https://github.com/algorand/algorand-sdk-testing/blob/48bee3e9cceb4d41a7a251f48914ed56ed73dcba/features/unit/v2indexerclient_paths.feature#L279. 

These tests remain unchanged, and all sdks are passing these tests.

**Review by algochoi — APPROVED** [review]
Looks good and targets the v2 branch correctly

**Review by winder — APPROVED** [review]

**Pull request merged**
