### PR TITLE
fixes, file renames

### PR DESCRIPTION
**Pull request by algonautshant**
- Replace `abc` with proper address.  `abc` will be rejected by the java sdk as invalid address.
- rename the new unlimited assets response file prefixes appropriately. 
- add newline at the end of the files

### CODE REVIEW

**Comment by tolikzinovyev** [comment]
Thanks.

Why have `unlimited_aa_` in the file names? Their directory already has `unlimited_assets_` in it.
Do you have a corresponding PR for the generator?

**Comment by algonautshant** [comment]
I am not particular about the naming. "applications" was wrong, so this is unlimited apps/assets (aa).
This is the generator update PR: https://github.com/algorand/generator/pull/26

**Comment by tolikzinovyev** [comment]
I think we should just erase `unlimited_aa_`. It's not needed.

**Comment by tolikzinovyev** [comment]
Did you modify the generator to add the newlines? I couldn't find that change. Also, I'm not sure newlines are really necessary.

**Comment by algonautshant** [comment]
the newlines at the end of the files are not added by the generator.

**Pull request merged**
